### ISSUE TITLE
Trouble installing hyperdex-client (node)

### ISSUE THREAD

**Issue by liammclennan** [rescrv/HyperDex#217]
Installing on Ubuntu 14.10. Error is:

```
configure: error: 
---------------------------------------
Replicant relies upon the popt library.
Please install popt to continue.
---------------------------------------
hyperdex-client.target.mk:13: recipe for target '.' failed
make: *** [.] Error 1
make: Leaving directory '/home/liam/hyperdex/node_modules/hyperdex-client/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.16.0-43-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/liam/hyperdex/node_modules/hyperdex-client
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! hyperdex-client@0.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hyperdex-client@0.0.7 install script.
npm ERR! This is most likely a problem with the hyperdex-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls hyperdex-client
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-43-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "hyperdex-client"
npm ERR! cwd /home/liam/hyperdex
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/liam/hyperdex/npm-debug.log
npm ERR! not ok code 0
liam@ubuntu:~/hyperdex$ This failure might be due to the use of legacy binary "node"
This: command not found
```

**Comment by BHSDuncan** [comment]
I'd like to add "me too", but on my Mac Book Pro running Yosemite 10.10.4.

**Comment by CU-0xff** [comment]
After installing libpopt-dev and running the installation with sudo, this error was going away ... but, well, bumped into another one ;-)

**Comment by el33th4x0r** [comment]
We're working on restoring support for OSX, following a regression in 1.8.

**Comment by n321203** [comment]
Any progress on this? 
Trying to install node bindings, but it fails with 
"Replicant relies upon the popt library. Please install popt to continue."

Using OS X 10.10.

**Comment by n321203** [comment]
Update: Just tried a fresh install on Ubuntu 14.04, it gives the same error. So this isn't just related to OS X.

Added popt with

`apt-get install libopt-dev`

which solved this error and produced a new one: Missing pkg-config. Ran

`apt-get install pkg-config`

which solved that error and produced a new one: Missing libhyperleveldb. 

No I am out of luck. Why should it be so hard to try this piece of software out. Can someone point me to a combination of OS + Hyperdex version + node-bindings which will actually install?
